## CONCATENATION DE TYPE UNION

In [1]:
import pandas as pd

In [13]:
# Deux Tables dont on veut faire l'UNION
df1 = pd.DataFrame([['A1','A2'],['Paris']],columns=['ID','VILLE'])
df2 = pd.DataFrame(['A3','A4'],columns=['ID'])
df3 = pd.DataFrame([['A5','A6'],['Londres']],columns=['ID2','VILLE'])
print(df1)
print(df2)
print(df3)

      ID VILLE
0     A1    A2
1  Paris  None
   ID
0  A3
1  A4
       ID2 VILLE
0       A5    A6
1  Londres  None

In [7]:
print(df1.columns)

RangeIndex(start=0, stop=2, step=1)

In [4]:
print(df1)
print(df2)

       0     1
0     A1    A2
1  Paris  None
    0
0  A3
1  A4

In [14]:
# UNION
pd.concat([df1, df2,df3],axis=0)

      ID VILLE      ID2
0     A1    A2      NaN
1  Paris  None      NaN
0     A3   NaN      NaN
1     A4   NaN      NaN
0    NaN    A6       A5
1    NaN  None  Londres

In [16]:
# APPEND
df1.append(df2).append(df3)

      ID VILLE      ID2
0     A1    A2      NaN
1  Paris  None      NaN
0     A3   NaN      NaN
1     A4   NaN      NaN
0    NaN    A6       A5
1    NaN  None  Londres