## CONCATENATION DE TYPE UNION

In [2]:

import pandas as pd

In [4]:
# Deux Tables dont on veut faire l'UNION
df1 = pd.DataFrame([['A1','A2'],['Paris']])
df2 = pd.DataFrame(['A3','A4'])
df3 = pd.DataFrame([['A5','A6'],['Londres']])
print(df1)
print(df2)

       0     1
0     A1    A2
1  Paris  None
    0
0  A3
1  A4

In [5]:
# Les col s'appellent pas pareil
df1.columns=['ID']
df2.columns=['ID2']
df3.columns=['ID']

ValueError: Length mismatch: Expected axis has 2 elements, new values have 1 elements

In [6]:
print(df1)
print(df2)

       0     1
0     A1    A2
1  Paris  None
    0
0  A3
1  A4

In [7]:
# UNION
pd.concat([df1, df2,df3],axis=0)

         0     1
0       A1    A2
1    Paris  None
0       A3   NaN
1       A4   NaN
0       A5    A6
1  Londres  None

In [8]:
# APPEND
df1.append(df2)

       0     1
0     A1    A2
1  Paris  None
0     A3   NaN
1     A4   NaN