In [2]:
import pandas as pd

In [21]:
# Deux Tables dont on veut faire l'UNION
df1 = pd.DataFrame(['A1','A2'],)
df2 = pd.DataFrame(['A3','A4'])
df3 = pd.DataFrame(['A5','A6'])
print(df1)
print(df2)

    0
0  A1
1  A2
    0
0  A3
1  A4

In [22]:
# Les col s'appellent pas pareil
df1.columns=['ID']
df2.columns=['ID2']
df3.columns=['ID']

In [23]:
print(df1)
print(df2)

   ID
0  A1
1  A2
  ID2
0  A3
1  A4

In [24]:
# UNION
pd.concat([df1, df2,df3],axis=0)

    ID  ID2
0   A1  NaN
1   A2  NaN
0  NaN   A3
1  NaN   A4
0   A5  NaN
1   A6  NaN

In [19]:
# APPEND
df1.append(df2)

    ID  ID2
0   A1  NaN
1   A2  NaN
0  NaN   A3
1  NaN   A4