# Nettoyer un dataframe grâce aux regex

In [4]:
# Import des librairies
import pandas as pd
import re 
import unidecode

In [2]:
# Création d'un jeu de données
data_df = pd.DataFrame(
    ['une autonomie de 10h'
     ,"jusqu'à 12h30 d'autonomie"
     ,"1 heure"
     ,"48 heures en veille et 12h en utilisation"
     ,"une autonomie meilleure que l'iphone X"
     ,"blabla"]
    , columns = ['autonomie']
)

In [3]:
data_df

                                   autonomie
0                       une autonomie de 10h
1                  jusqu'à 12h30 d'autonomie
2                                    1 heure
3  48 heures en veille et 12h en utilisation
4     une autonomie meilleure que l'iphone X
5                                     blabla

In [25]:
# STEP 1 : Ecrire une fonction qui permet de normaliser l'écriture des heures 
def normalisation_heure(str_enentree):
    ch = unidecode.unidecode(str_enentree.lower())
    ch = ch.replace("heures","h").replace("heure","h").replace(" et ",", ")
    split_ch = ch.split(',')
    res = []
    for element in split_ch :
        # pattern 10h30, 10 h 30 
        if re.search("[0-9]{1,2}\s{0,1}[h]\s{0,1}[0-9]{1,2}",element):
            res+= [re.sub("([0-9]{1,2})\s{0,1}[h]\s{0,1}([0-9]{1,2})","\\1h\\2",element)]
        # pattern 10h 10 h
        elif re.search("[0-9]{1,2}\s{0,1}[h]",ch):
            res+=[re.sub("([0-9]{1,2})\s{0,1}[h]","\\1h",element)]
        else:
            res+= [element]
    return ",".join(res)

In [26]:
chaine1="1h, 1h30, 1 h, 1 h 30, 1 heure, 2 heures et 2 heures 30"
normalisation_heure(chaine1)

'1h, 1h30, 1h, 1h30, 1h, 2h, 2h30'

In [27]:
# STEP 2 : Appliquer à chacune des lignes
data_df['autonomie_normalize']=data_df['autonomie'].apply(lambda x:normalisation_heure(x))

In [28]:
data_df

,autonomie,autonomie_normalize
0,une autonomie de 10h,une autonomie de 10h
1,jusqu'à 12h30 d'autonomie,jusqu'a 12h30 d'autonomie
2,1 heure,1h
3,48 heures en veille et 12h en utilisation,"48h en veille, 12h en utilisation"
4,une autonomie meilleure que l'iphone X,une autonomie meilleure que l'iphone x
5,blabla,blabla